INFO:root:2017-07-04 11:02:39	starting
WARNING:root:hpmini-srvr:9000/socket.io [waiting for connection] HTTPConnectionPool(host='hpmini-srvr', port=9000): Max retries exceeded with url: /socket.io/?EIO=3&transport=polling&t=1499180559847-0 (Caused by NewConnectionError('<urllib3.connection.HTTPConnection object at 0x00000221467D1CC0>: Failed to establish a new connection: [WinError 10060] A connection attempt failed because the connected party did not properly respond after a period of time, or established connection failed because connected host has failed to respond',))
WARNING:root:hpmini-srvr:9000/socket.io [waiting for connection] HTTPConnectionPool(host='hpmini-srvr', port=9000): Max retries exceeded with url: /socket.io/?EIO=3&transport=polling&t=1499180581919-0 (Caused by NewConnectionError('<urllib3.connection.HTTPConnection object at 0x00000221467D1CF8>: Failed to establish a new connection: [WinError 10060] A connection attempt failed because the connected party did not properly respond after a period of time, or established connection failed because connected host has failed to respond',))
WARNING:root:hpmini-srvr:9000/socket.io [waiting for connection] HTTPConnectionPool(host='hpmini-srvr', port=9000): Max retries exceeded with url: /socket.io/?EIO=3&transport=polling&t=1499180603964-0 (Caused by NewConnectionError('<urllib3.connection.HTTPConnection object at 0x00000221467FB0F0>: Failed to establish a new connection: [WinError 10060] A connection attempt failed because the connected party did not properly respond after a period of time, or established connection failed because connected host has failed to respond',))
WARNING:root:hpmini-srvr:9000/socket.io [waiting for connection] HTTPConnectionPool(host='hpmini-srvr', port=9000): Max retries exceeded with url: /socket.io/?EIO=3&transport=polling&t=1499180626013-0 (Caused by NewConnectionError('<urllib3.connection.HTTPConnection object at 0x00000221467FB4E0>: Failed to establish a new connection: [WinError 10060] A connection attempt failed because the connected party did not properly respond after a period of time, or established connection failed because connected host has failed to respond',))
WARNING:root:hpmini-srvr:9000/socket.io [waiting for connection] HTTPConnectionPool(host='hpmini-srvr', port=9000): Max retries exceeded with url: /socket.io/?EIO=3&transport=polling&t=1499180648057-0 (Caused by NewConnectionError('<urllib3.connection.HTTPConnection object at 0x00000221467FB8D0>: Failed to establish a new connection: [WinError 10060] A connection attempt failed because the connected party did not properly respond after a period of time, or established connection failed because connected host has failed to respond',))
INFO:root:2017-07-04 11:04:48	starting
INFO:root:2017-07-04 11:05:05	starting
WARNING:root:localhost:9000/socket.io [waiting for connection] HTTPConnectionPool(host='localhost', port=9000): Max retries exceeded with url: /socket.io/?EIO=3&transport=polling&t=1499180706021-0 (Caused by NewConnectionError('<urllib3.connection.HTTPConnection object at 0x0000026694332C88>: Failed to establish a new connection: [WinError 10061] No connection could be made because the target machine actively refused it',))
WARNING:root:localhost:9000/socket.io [waiting for connection] HTTPConnectionPool(host='localhost', port=9000): Max retries exceeded with url: /socket.io/?EIO=3&transport=polling&t=1499180709065-0 (Caused by NewConnectionError('<urllib3.connection.HTTPConnection object at 0x0000026694328FD0>: Failed to establish a new connection: [WinError 10061] No connection could be made because the target machine actively refused it',))
WARNING:root:localhost:9000/socket.io [waiting for connection] HTTPConnectionPool(host='localhost', port=9000): Max retries exceeded with url: /socket.io/?EIO=3&transport=polling&t=1499180712103-0 (Caused by NewConnectionError('<urllib3.connection.HTTPConnection object at 0x000002669435C0B8>: Failed to establish a new connection: [WinError 10061] No connection could be made because the target machine actively refused it',))
WARNING:root:localhost:9000/socket.io [waiting for connection] HTTPConnectionPool(host='localhost', port=9000): Max retries exceeded with url: /socket.io/?EIO=3&transport=polling&t=1499180715135-0 (Caused by NewConnectionError('<urllib3.connection.HTTPConnection object at 0x000002669435C4A8>: Failed to establish a new connection: [WinError 10061] No connection could be made because the target machine actively refused it',))
WARNING:root:localhost:9000/socket.io [waiting for connection] HTTPConnectionPool(host='localhost', port=9000): Max retries exceeded with url: /socket.io/?EIO=3&transport=polling&t=1499180718187-0 (Caused by NewConnectionError('<urllib3.connection.HTTPConnection object at 0x000002669435C898>: Failed to establish a new connection: [WinError 10061] No connection could be made because the target machine actively refused it',))
WARNING:root:localhost:9000/socket.io [waiting for connection] HTTPConnectionPool(host='localhost', port=9000): Max retries exceeded with url: /socket.io/?EIO=3&transport=polling&t=1499180721224-0 (Caused by NewConnectionError('<urllib3.connection.HTTPConnection object at 0x000002669435CC88>: Failed to establish a new connection: [WinError 10061] No connection could be made because the target machine actively refused it',))
WARNING:root:localhost:9000/socket.io [waiting for connection] HTTPConnectionPool(host='localhost', port=9000): Max retries exceeded with url: /socket.io/?EIO=3&transport=polling&t=1499180724243-0 (Caused by NewConnectionError('<urllib3.connection.HTTPConnection object at 0x000002669436D0B8>: Failed to establish a new connection: [WinError 10061] No connection could be made because the target machine actively refused it',))
WARNING:root:localhost:9000/socket.io [waiting for connection] HTTPConnectionPool(host='localhost', port=9000): Max retries exceeded with url: /socket.io/?EIO=3&transport=polling&t=1499180727284-0 (Caused by NewConnectionError('<urllib3.connection.HTTPConnection object at 0x000002669436D4A8>: Failed to establish a new connection: [WinError 10061] No connection could be made because the target machine actively refused it',))
WARNING:root:localhost:9000/socket.io [waiting for connection] HTTPConnectionPool(host='localhost', port=9000): Max retries exceeded with url: /socket.io/?EIO=3&transport=polling&t=1499180730304-0 (Caused by NewConnectionError('<urllib3.connection.HTTPConnection object at 0x000002669436D898>: Failed to establish a new connection: [WinError 10061] No connection could be made because the target machine actively refused it',))
WARNING:root:localhost:9000/socket.io [waiting for connection] HTTPConnectionPool(host='localhost', port=9000): Max retries exceeded with url: /socket.io/?EIO=3&transport=polling&t=1499180733342-0 (Caused by NewConnectionError('<urllib3.connection.HTTPConnection object at 0x000002669435CA58>: Failed to establish a new connection: [WinError 10061] No connection could be made because the target machine actively refused it',))
WARNING:root:localhost:9000/socket.io [waiting for connection] HTTPConnectionPool(host='localhost', port=9000): Max retries exceeded with url: /socket.io/?EIO=3&transport=polling&t=1499180736376-0 (Caused by NewConnectionError('<urllib3.connection.HTTPConnection object at 0x000002669435C668>: Failed to establish a new connection: [WinError 10061] No connection could be made because the target machine actively refused it',))
WARNING:root:localhost:9000/socket.io [waiting for connection] HTTPConnectionPool(host='localhost', port=9000): Max retries exceeded with url: /socket.io/?EIO=3&transport=polling&t=1499180739404-0 (Caused by NewConnectionError('<urllib3.connection.HTTPConnection object at 0x000002669435C518>: Failed to establish a new connection: [WinError 10061] No connection could be made because the target machine actively refused it',))
WARNING:root:localhost:9000/socket.io [waiting for connection] HTTPConnectionPool(host='localhost', port=9000): Max retries exceeded with url: /socket.io/?EIO=3&transport=polling&t=1499180742422-0 (Caused by NewConnectionError('<urllib3.connection.HTTPConnection object at 0x00000266934B3780>: Failed to establish a new connection: [WinError 10061] No connection could be made because the target machine actively refused it',))
WARNING:root:localhost:9000/socket.io [waiting for connection] HTTPConnectionPool(host='localhost', port=9000): Max retries exceeded with url: /socket.io/?EIO=3&transport=polling&t=1499180745463-0 (Caused by NewConnectionError('<urllib3.connection.HTTPConnection object at 0x0000026694332D30>: Failed to establish a new connection: [WinError 10061] No connection could be made because the target machine actively refused it',))
WARNING:root:localhost:9000/socket.io [waiting for connection] HTTPConnectionPool(host='localhost', port=9000): Max retries exceeded with url: /socket.io/?EIO=3&transport=polling&t=1499180748495-0 (Caused by NewConnectionError('<urllib3.connection.HTTPConnection object at 0x000002669436D438>: Failed to establish a new connection: [WinError 10061] No connection could be made because the target machine actively refused it',))
WARNING:root:localhost:9000/socket.io [waiting for connection] HTTPConnectionPool(host='localhost', port=9000): Max retries exceeded with url: /socket.io/?EIO=3&transport=polling&t=1499180751549-0 (Caused by NewConnectionError('<urllib3.connection.HTTPConnection object at 0x000002669436D9E8>: Failed to establish a new connection: [WinError 10061] No connection could be made because the target machine actively refused it',))
WARNING:root:localhost:9000/socket.io [waiting for connection] HTTPConnectionPool(host='localhost', port=9000): Max retries exceeded with url: /socket.io/?EIO=3&transport=polling&t=1499180754584-0 (Caused by NewConnectionError('<urllib3.connection.HTTPConnection object at 0x000002669436DE10>: Failed to establish a new connection: [WinError 10061] No connection could be made because the target machine actively refused it',))
WARNING:root:localhost:9000/socket.io [waiting for connection] HTTPConnectionPool(host='localhost', port=9000): Max retries exceeded with url: /socket.io/?EIO=3&transport=polling&t=1499180757641-0 (Caused by NewConnectionError('<urllib3.connection.HTTPConnection object at 0x00000266943AF240>: Failed to establish a new connection: [WinError 10061] No connection could be made because the target machine actively refused it',))
WARNING:root:localhost:9000/socket.io [waiting for connection] HTTPConnectionPool(host='localhost', port=9000): Max retries exceeded with url: /socket.io/?EIO=3&transport=polling&t=1499180760698-0 (Caused by NewConnectionError('<urllib3.connection.HTTPConnection object at 0x0000026694328DA0>: Failed to establish a new connection: [WinError 10061] No connection could be made because the target machine actively refused it',))
WARNING:root:localhost:9000/socket.io [waiting for connection] HTTPConnectionPool(host='localhost', port=9000): Max retries exceeded with url: /socket.io/?EIO=3&transport=polling&t=1499180763736-0 (Caused by NewConnectionError('<urllib3.connection.HTTPConnection object at 0x0000026694332F60>: Failed to establish a new connection: [WinError 10061] No connection could be made because the target machine actively refused it',))
WARNING:root:localhost:9000/socket.io [waiting for connection] HTTPConnectionPool(host='localhost', port=9000): Max retries exceeded with url: /socket.io/?EIO=3&transport=polling&t=1499180766766-0 (Caused by NewConnectionError('<urllib3.connection.HTTPConnection object at 0x000002669435C048>: Failed to establish a new connection: [WinError 10061] No connection could be made because the target machine actively refused it',))
WARNING:root:localhost:9000/socket.io [waiting for connection] HTTPConnectionPool(host='localhost', port=9000): Max retries exceeded with url: /socket.io/?EIO=3&transport=polling&t=1499180769820-0 (Caused by NewConnectionError('<urllib3.connection.HTTPConnection object at 0x000002669435C400>: Failed to establish a new connection: [WinError 10061] No connection could be made because the target machine actively refused it',))
WARNING:root:localhost:9000/socket.io [waiting for connection] HTTPConnectionPool(host='localhost', port=9000): Max retries exceeded with url: /socket.io/?EIO=3&transport=polling&t=1499180772857-0 (Caused by NewConnectionError('<urllib3.connection.HTTPConnection object at 0x000002669435CF28>: Failed to establish a new connection: [WinError 10061] No connection could be made because the target machine actively refused it',))
WARNING:root:localhost:9000/socket.io [waiting for connection] HTTPConnectionPool(host='localhost', port=9000): Max retries exceeded with url: /socket.io/?EIO=3&transport=polling&t=1499180775887-0 (Caused by NewConnectionError('<urllib3.connection.HTTPConnection object at 0x000002669435CF98>: Failed to establish a new connection: [WinError 10061] No connection could be made because the target machine actively refused it',))
WARNING:root:localhost:9000/socket.io [waiting for connection] HTTPConnectionPool(host='localhost', port=9000): Max retries exceeded with url: /socket.io/?EIO=3&transport=polling&t=1499180778916-0 (Caused by NewConnectionError('<urllib3.connection.HTTPConnection object at 0x000002669436DDD8>: Failed to establish a new connection: [WinError 10061] No connection could be made because the target machine actively refused it',))
WARNING:root:localhost:9000/socket.io [waiting for connection] HTTPConnectionPool(host='localhost', port=9000): Max retries exceeded with url: /socket.io/?EIO=3&transport=polling&t=1499180781948-0 (Caused by NewConnectionError('<urllib3.connection.HTTPConnection object at 0x000002669436DBA8>: Failed to establish a new connection: [WinError 10061] No connection could be made because the target machine actively refused it',))
WARNING:root:localhost:9000/socket.io [waiting for connection] HTTPConnectionPool(host='localhost', port=9000): Max retries exceeded with url: /socket.io/?EIO=3&transport=polling&t=1499180785000-0 (Caused by NewConnectionError('<urllib3.connection.HTTPConnection object at 0x000002669436D438>: Failed to establish a new connection: [WinError 10061] No connection could be made because the target machine actively refused it',))
INFO:root:2017-07-04 11:06:49	starting
WARNING:root:localhost:9000/socket.io [waiting for connection] HTTPConnectionPool(host='localhost', port=9000): Max retries exceeded with url: /socket.io/?EIO=3&transport=polling&t=1499180813244-0 (Caused by NewConnectionError('<urllib3.connection.HTTPConnection object at 0x000002CB6ABE3630>: Failed to establish a new connection: [WinError 10061] No connection could be made because the target machine actively refused it',))
INFO:root:2017-07-04 11:07:43	starting
WARNING:root:localhost:9000/socket.io [waiting for connection] HTTPConnectionPool(host='localhost', port=9000): Max retries exceeded with url: /socket.io/?EIO=3&transport=polling&t=1499180863735-0 (Caused by NewConnectionError('<urllib3.connection.HTTPConnection object at 0x00000220679E2C88>: Failed to establish a new connection: [WinError 10061] No connection could be made because the target machine actively refused it',))
WARNING:root:localhost:9000/socket.io [waiting for connection] HTTPConnectionPool(host='localhost', port=9000): Max retries exceeded with url: /socket.io/?EIO=3&transport=polling&t=1499180866770-0 (Caused by NewConnectionError('<urllib3.connection.HTTPConnection object at 0x00000220679D8FD0>: Failed to establish a new connection: [WinError 10061] No connection could be made because the target machine actively refused it',))
INFO:root:2017-07-04 11:08:02	starting
WARNING:root:localhost:9000/socket.io [waiting for connection] HTTPConnectionPool(host='localhost', port=9000): Max retries exceeded with url: /socket.io/?EIO=3&transport=polling&t=1499180897030-0 (Caused by NewConnectionError('<urllib3.connection.HTTPConnection object at 0x000001DC0C2F3208>: Failed to establish a new connection: [WinError 10061] No connection could be made because the target machine actively refused it',))
WARNING:root:localhost:9000/socket.io [waiting for connection] HTTPConnectionPool(host='localhost', port=9000): Max retries exceeded with url: /socket.io/?EIO=3&transport=polling&t=1499180900105-0 (Caused by NewConnectionError('<urllib3.connection.HTTPConnection object at 0x000001DC0C31F080>: Failed to establish a new connection: [WinError 10061] No connection could be made because the target machine actively refused it',))
WARNING:root:localhost:9000/socket.io [waiting for connection] HTTPConnectionPool(host='localhost', port=9000): Max retries exceeded with url: /socket.io/?EIO=3&transport=polling&t=1499180903164-0 (Caused by NewConnectionError('<urllib3.connection.HTTPConnection object at 0x000001DC0C31F470>: Failed to establish a new connection: [WinError 10061] No connection could be made because the target machine actively refused it',))
WARNING:root:localhost:9000/socket.io [waiting for connection] HTTPConnectionPool(host='localhost', port=9000): Max retries exceeded with url: /socket.io/?EIO=3&transport=polling&t=1499180906223-0 (Caused by NewConnectionError('<urllib3.connection.HTTPConnection object at 0x000001DC0C31F860>: Failed to establish a new connection: [WinError 10061] No connection could be made because the target machine actively refused it',))
WARNING:root:localhost:9000/socket.io [waiting for connection] HTTPConnectionPool(host='localhost', port=9000): Max retries exceeded with url: /socket.io/?EIO=3&transport=polling&t=1499180909280-0 (Caused by NewConnectionError('<urllib3.connection.HTTPConnection object at 0x000001DC0C31FC50>: Failed to establish a new connection: [WinError 10061] No connection could be made because the target machine actively refused it',))
INFO:root:2017-07-04 11:08:53	starting
WARNING:root:localhost:9000/socket.io [waiting for connection] HTTPConnectionPool(host='localhost', port=9000): Max retries exceeded with url: /socket.io/?EIO=3&transport=polling&t=1499180938215-0 (Caused by NewConnectionError('<urllib3.connection.HTTPConnection object at 0x00000187ED165F98>: Failed to establish a new connection: [WinError 10061] No connection could be made because the target machine actively refused it',))
WARNING:root:localhost:9000/socket.io [waiting for connection] HTTPConnectionPool(host='localhost', port=9000): Max retries exceeded with url: /socket.io/?EIO=3&transport=polling&t=1499180941297-0 (Caused by NewConnectionError('<urllib3.connection.HTTPConnection object at 0x00000187ED18F080>: Failed to establish a new connection: [WinError 10061] No connection could be made because the target machine actively refused it',))
WARNING:root:localhost:9000/socket.io [waiting for connection] HTTPConnectionPool(host='localhost', port=9000): Max retries exceeded with url: /socket.io/?EIO=3&transport=polling&t=1499180944353-0 (Caused by NewConnectionError('<urllib3.connection.HTTPConnection object at 0x00000187ED18F470>: Failed to establish a new connection: [WinError 10061] No connection could be made because the target machine actively refused it',))
INFO:root:2017-07-04 11:09:41	starting
INFO:root:2017-07-04 11:10:35	starting
INFO:root:2017-07-04 11:24:06	starting
INFO:root:2017-07-04 11:25:04	starting
INFO:root:2017-07-04 11:25:17	starting
INFO:root:2017-07-04 11:26:05	starting
INFO:root:2017-07-04 11:27:58	starting
INFO:root:2017-07-04 11:30:25	starting
WARNING:root:dellws:9000/socket.io [waiting for connection] HTTPConnectionPool(host='dellws', port=9000): Max retries exceeded with url: /socket.io/?EIO=3&transport=polling&t=1499182236630-0 (Caused by NewConnectionError('<urllib3.connection.HTTPConnection object at 0x00000281017F3DD8>: Failed to establish a new connection: [WinError 10061] No connection could be made because the target machine actively refused it',))
INFO:root:2017-07-04 11:30:49	hi temp:79.0
ERROR:root:2017-07-04 12:30:53	'datetime.timedelta' object has no attribute 'hours'
ERROR:root:2017-07-04 12:30:59	'datetime.timedelta' object has no attribute 'hours'
ERROR:root:2017-07-04 12:31:04	'datetime.timedelta' object has no attribute 'hours'
ERROR:root:2017-07-04 12:31:09	'datetime.timedelta' object has no attribute 'hours'
ERROR:root:2017-07-04 12:31:14	'datetime.timedelta' object has no attribute 'hours'
ERROR:root:2017-07-04 12:31:20	'datetime.timedelta' object has no attribute 'hours'
ERROR:root:2017-07-04 12:31:25	'datetime.timedelta' object has no attribute 'hours'
ERROR:root:2017-07-04 12:31:30	'datetime.timedelta' object has no attribute 'hours'
ERROR:root:2017-07-04 12:31:36	'datetime.timedelta' object has no attribute 'hours'
ERROR:root:2017-07-04 12:31:41	'datetime.timedelta' object has no attribute 'hours'
ERROR:root:2017-07-04 12:31:46	'datetime.timedelta' object has no attribute 'hours'
ERROR:root:2017-07-04 12:31:52	'datetime.timedelta' object has no attribute 'hours'
ERROR:root:2017-07-04 12:31:57	'datetime.timedelta' object has no attribute 'hours'
ERROR:root:2017-07-04 12:32:03	'datetime.timedelta' object has no attribute 'hours'
ERROR:root:2017-07-04 12:32:08	'datetime.timedelta' object has no attribute 'hours'
ERROR:root:2017-07-04 12:32:13	'datetime.timedelta' object has no attribute 'hours'
ERROR:root:2017-07-04 12:32:19	'datetime.timedelta' object has no attribute 'hours'
ERROR:root:2017-07-04 12:32:24	'datetime.timedelta' object has no attribute 'hours'
ERROR:root:2017-07-04 12:32:29	'datetime.timedelta' object has no attribute 'hours'
ERROR:root:2017-07-04 12:32:35	'datetime.timedelta' object has no attribute 'hours'
ERROR:root:2017-07-04 12:32:40	'datetime.timedelta' object has no attribute 'hours'
ERROR:root:2017-07-04 12:33:05	bytearray index out of range
ERROR:root:2017-07-04 12:33:31	'datetime.timedelta' object has no attribute 'hours'
INFO:root:2017-07-04 13:43:39	starting
INFO:root:2017-07-04 13:43:41	hi temp:84.5
